-- DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id                integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app               varchar                                 NOT NULL,
    uri               varchar                                 NOT NULL,
    ip                varchar(15)                             NOT NULL,
    request_timestamp timestamp without time zone             NOT NULL,
    CONSTRAINT hits_pkey PRIMARY KEY (id)
);